default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--all-targets",
    "--color", "always",
]
need_stdout = false

[jobs.test]
command = [
    "cargo", "test", "--color", "always",
    "--", "--color", "always", # see https://github.com/Canop/bacon/issues/124
]
need_stdout = true

[jobs.covtest]
command = [
    "cargo", "llvm-cov", "--branch", "--show-missing-lines",
    "--color", "always", "--", "--color", "always",
]
need_stdout = true
env.RUSTFLAGS = ""
env.CARGO_TARGET_DIR = "target/llvm-cov-target"
env.CARGO_LLVM_COV_TARGET_DIR = "target/llvm-cov-target"

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"

[jobs.run]
command = [
    "cargo", "run",
    "--color", "always",
]
need_stdout = true
allow_warnings = true
background = true

[jobs.fmt]
command = ["cargo", "fmt"]
need_stdout = false
on_success = "back"

[keybindings]
f = "job:fmt"
shift-t = "job:covtest"
