name: coverage

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: install cargo-llvm-cov
        run: |
          cargo install --locked cargo-llvm-cov@0.6.8
      - name: collect coverage information
        run: |
          cargo llvm-cov --branch --text
