name: pre-commit

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-04-27
          components: rustfmt, clippy
      - name: Install `cargo-insta`
        run: |
          curl -LsSf https://insta.rs/install.sh | sh
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--hook-stage=manual"
