name: pre-commit

on:
  push:
    tags: '*'
    branches:
      - main
      - 'test-me-*'
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-05-06
          # we have to install miri here even though it’s unused, otherwise it
          # would get installed via `rust-toolchain.toml` when running `cargo
          # fmt`, which conflicts with the rust-toolchain installed rust.
          components: rustfmt, clippy, miri, rustc-codegen-cranelift
      - name: Install `cargo-insta`
        run: |
          curl -LsSf https://insta.rs/install.sh | sh
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--hook-stage=manual"
